import type { SIPCategory } from "./data"

export const sipCategories: Record<number, SIPCategory[]> = {
  1: ["Process"],
  2: ["Dev Tools"],
  3: ["Wallet UX & Security"],
  4: ["Dev Tools"],
  5: ["Economics"],
  6: ["Staking & Liquid Staking"],
  7: ["Dev Tools"],
  8: ["Dev Tools"],
  9: ["Wallet UX & Security"],
  10: ["Wallet UX & Security"],
  11: ["Dev Tools"],
  12: ["Crypto Primitives"],
  13: ["Dev Tools"],
  14: ["Dev Tools"],
  15: ["Wallet UX & Security"],
  16: ["Dev Tools"],
  17: ["Dev Tools"],
  18: ["Dev Tools"],
  19: ["Dev Tools"],
  20: ["Staking & Liquid Staking"],
  21: ["Wallet UX & Security"],
  22: ["Dev Tools"],
  23: ["Wallet UX & Security"],
  24: ["Wallet UX & Security"],
  25: ["Wallet UX & Security"],
  26: ["Wallet UX & Security"],
  27: ["Wallet UX & Security"],
  28: ["Wallet UX & Security"],
  29: ["Wallet UX & Security"],
  30: ["Wallet UX & Security"],
  31: ["Staking & Liquid Staking"],
  32: ["Staking & Liquid Staking"],
  33: ["Staking & Liquid Staking"],
  34: ["Wallet UX & Security"],
  35: ["Wallet UX & Security"],
  36: ["Wallet UX & Security"],
  37: ["Dev Tools"],
  38: ["Crypto Primitives"],
  39: ["Staking & Validators"],
  40: ["Core"],
  41: ["Wallet UX & Security"],
  42: ["Wallet UX & Security"],
  43: ["Wallet UX & Security"],
  44: ["Core"],
  45: ["Gas"],
  46: ["Wallet UX & Security"],
  47: ["Wallet UX & Security"],
  48: ["Gas"],
  49: ["Gas"],
  50: ["Process"],
  51: ["Networking & Mempool"],
  52: ["Dev Tools"],
  53: ["Dev Tools"],
  54: ["Wallet UX & Security"],
  55: ["Dev Tools"],
  56: ["Wallet UX & Security"],
  57: ["Dev Tools"],
  58: ["Dev Tools"],
  59: ["Object Lifecycle"],
}
