import type { SIPCategory } from "./data"

export const sipCategories: Record<number, SIPCategory> = {
  1: "Governance / Process",
  2: "Dev Tools",
  3: "Wallet UX & Security",
  4: "Dev Tools",
  5: "Governance / Process",
  6: "Staking & Liquid Staking",
  7: "Gas / Economics",
  8: "Dev Tools",
  9: "Wallet UX & Security",
  10: "Wallet UX & Security",
  11: "Dev Tools",
  12: "Crypto Primitives",
  13: "Dev Tools",
  14: "Dev Tools",
  15: "Wallet UX & Security",
  16: "Dev Tools",
  17: "Dev Tools",
  18: "Gas / Economics",
  19: "Gas / Economics",
  20: "Staking & Liquid Staking",
  21: "Wallet UX & Security",
  22: "Wallet UX & Security",
  23: "Gas / Economics",
  24: "Crypto Primitives",
  25: "Dev Tools",
  26: "Staking & Validators",
  27: "Gas / Economics",
  28: "Wallet UX & Security",
  29: "Wallet UX & Security",
  30: "Dev Tools",
  31: "Staking & Liquid Staking",
  32: "Gas / Economics",
  33: "Dev Tools",
  34: "Dev Tools",
  35: "Dev Tools",
  36: "Core / Storage",
  37: "Dev Tools",
  38: "Crypto Primitives",
  39: "Staking & Validators",
  40: "Core / Object Lifecycle",
  41: "Wallet UX & Security",
  42: "Networking & Mempool",
  43: "Core / Storage",
  44: "Dev Tools",
  45: "Gas / Economics",
  46: "Dev Tools",
  47: "Wallet UX & Security",
  48: "Dev Tools",
  49: "Gas / Economics",
  50: "Governance / Process",
  51: "Dev Tools",
  52: "Dev Tools",
  53: "Dev Tools",
  54: "Crypto Primitives",
  55: "Core / Storage",
  56: "Wallet UX & Security",
  57: "Staking & Liquid Staking",
  58: "Interop",
  59: "Core / Object Lifecycle",
}
